// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	// идентификатор
	ID string `json:"id"`
	// какой-то текст
	Text string `json:"text"`
	// вот фишка
	Done bool `json:"done"`
	// пользователь
	User *User `json:"user"`
	// дата и время
	CreateAt *time.Time `json:"create_at"`
	// роль пользователя
	Role Role `json:"role"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Role string

const (
	RoleAdmin  Role = "ADMIN"
	RoleGuest  Role = "GUEST"
	RoleLogist Role = "LOGIST"
	RoleTk     Role = "TK"
)

var AllRole = []Role{
	RoleAdmin,
	RoleGuest,
	RoleLogist,
	RoleTk,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleGuest, RoleLogist, RoleTk:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
