// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sungora.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhoneType int32

const (
	PhoneType_MOBILE PhoneType = 0
	PhoneType_HOME   PhoneType = 1
	PhoneType_WORK   PhoneType = 2
)

var PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}

func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b4b3d487cb6bc74, []int{0}
}

type TestReply_StatusOrders int32

const (
	TestReply_DRAFT  TestReply_StatusOrders = 0
	TestReply_NEW    TestReply_StatusOrders = 1
	TestReply_WORK   TestReply_StatusOrders = 2
	TestReply_CANCEL TestReply_StatusOrders = 3
	TestReply_CLOSE  TestReply_StatusOrders = 4
)

var TestReply_StatusOrders_name = map[int32]string{
	0: "DRAFT",
	1: "NEW",
	2: "WORK",
	3: "CANCEL",
	4: "CLOSE",
}

var TestReply_StatusOrders_value = map[string]int32{
	"DRAFT":  0,
	"NEW":    1,
	"WORK":   2,
	"CANCEL": 3,
	"CLOSE":  4,
}

func (x TestReply_StatusOrders) String() string {
	return proto.EnumName(TestReply_StatusOrders_name, int32(x))
}

func (TestReply_StatusOrders) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b4b3d487cb6bc74, []int{1, 0}
}

// The request message
type TestRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRequest) Reset()         { *m = TestRequest{} }
func (m *TestRequest) String() string { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()    {}
func (*TestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b4b3d487cb6bc74, []int{0}
}

func (m *TestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequest.Unmarshal(m, b)
}
func (m *TestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequest.Marshal(b, m, deterministic)
}
func (m *TestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequest.Merge(m, src)
}
func (m *TestRequest) XXX_Size() int {
	return xxx_messageInfo_TestRequest.Size(m)
}
func (m *TestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequest proto.InternalMessageInfo

func (m *TestRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message
type TestReply struct {
	Message              string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Cnt1                 int64                  `protobuf:"varint,2,opt,name=cnt1,proto3" json:"cnt1,omitempty"`
	Cnt2                 uint64                 `protobuf:"varint,3,opt,name=cnt2,proto3" json:"cnt2,omitempty"`
	Cnt3                 int32                  `protobuf:"varint,4,opt,name=cnt3,proto3" json:"cnt3,omitempty"`
	Cnt4                 uint32                 `protobuf:"varint,5,opt,name=cnt4,proto3" json:"cnt4,omitempty"`
	Flag                 bool                   `protobuf:"varint,6,opt,name=flag,proto3" json:"flag,omitempty"`
	Price                float32                `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	Summa                float64                `protobuf:"fixed64,8,opt,name=summa,proto3" json:"summa,omitempty"`
	Data                 []byte                 `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	Status               TestReply_StatusOrders `protobuf:"varint,10,opt,name=status,proto3,enum=proto.TestReply_StatusOrders" json:"status,omitempty"`
	Phone                []*PhoneNumber         `protobuf:"bytes,11,rep,name=phone,proto3" json:"phone,omitempty"`
	AdditionalTime       *timestamp.Timestamp   `protobuf:"bytes,12,opt,name=additional_time,json=additionalTime,proto3" json:"additional_time,omitempty"`
	Any                  *any.Any               `protobuf:"bytes,13,opt,name=any,proto3" json:"any,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TestReply) Reset()         { *m = TestReply{} }
func (m *TestReply) String() string { return proto.CompactTextString(m) }
func (*TestReply) ProtoMessage()    {}
func (*TestReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b4b3d487cb6bc74, []int{1}
}

func (m *TestReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestReply.Unmarshal(m, b)
}
func (m *TestReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestReply.Marshal(b, m, deterministic)
}
func (m *TestReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestReply.Merge(m, src)
}
func (m *TestReply) XXX_Size() int {
	return xxx_messageInfo_TestReply.Size(m)
}
func (m *TestReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TestReply.DiscardUnknown(m)
}

var xxx_messageInfo_TestReply proto.InternalMessageInfo

func (m *TestReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TestReply) GetCnt1() int64 {
	if m != nil {
		return m.Cnt1
	}
	return 0
}

func (m *TestReply) GetCnt2() uint64 {
	if m != nil {
		return m.Cnt2
	}
	return 0
}

func (m *TestReply) GetCnt3() int32 {
	if m != nil {
		return m.Cnt3
	}
	return 0
}

func (m *TestReply) GetCnt4() uint32 {
	if m != nil {
		return m.Cnt4
	}
	return 0
}

func (m *TestReply) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func (m *TestReply) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TestReply) GetSumma() float64 {
	if m != nil {
		return m.Summa
	}
	return 0
}

func (m *TestReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TestReply) GetStatus() TestReply_StatusOrders {
	if m != nil {
		return m.Status
	}
	return TestReply_DRAFT
}

func (m *TestReply) GetPhone() []*PhoneNumber {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *TestReply) GetAdditionalTime() *timestamp.Timestamp {
	if m != nil {
		return m.AdditionalTime
	}
	return nil
}

func (m *TestReply) GetAny() *any.Any {
	if m != nil {
		return m.Any
	}
	return nil
}

type PhoneNumber struct {
	Number               string    `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PhoneNumber) Reset()         { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()    {}
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b4b3d487cb6bc74, []int{2}
}

func (m *PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumber.Unmarshal(m, b)
}
func (m *PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumber.Merge(m, src)
}
func (m *PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_PhoneNumber.Size(m)
}
func (m *PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumber proto.InternalMessageInfo

func (m *PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *PhoneNumber) GetType() PhoneType {
	if m != nil {
		return m.Type
	}
	return PhoneType_MOBILE
}

type Person struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email                string         `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                []*PhoneNumber `protobuf:"bytes,4,rep,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b4b3d487cb6bc74, []int{3}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhone() []*PhoneNumber {
	if m != nil {
		return m.Phone
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.PhoneType", PhoneType_name, PhoneType_value)
	proto.RegisterEnum("proto.TestReply_StatusOrders", TestReply_StatusOrders_name, TestReply_StatusOrders_value)
	proto.RegisterType((*TestRequest)(nil), "proto.TestRequest")
	proto.RegisterType((*TestReply)(nil), "proto.TestReply")
	proto.RegisterType((*PhoneNumber)(nil), "proto.PhoneNumber")
	proto.RegisterType((*Person)(nil), "proto.Person")
}

func init() { proto.RegisterFile("sungora.proto", fileDescriptor_7b4b3d487cb6bc74) }

var fileDescriptor_7b4b3d487cb6bc74 = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x5d, 0x6b, 0xdb, 0x30,
	0x14, 0xad, 0xe2, 0x8f, 0xd4, 0x37, 0x6d, 0x66, 0x44, 0x19, 0x5a, 0x60, 0x4c, 0x33, 0x63, 0x88,
	0x0d, 0x5c, 0xe6, 0x64, 0xcf, 0x23, 0xcb, 0x32, 0x3a, 0x9a, 0x26, 0x45, 0x09, 0xe4, 0x71, 0x28,
	0xb5, 0x9a, 0x19, 0xfc, 0x35, 0x7f, 0x3c, 0xf8, 0xbf, 0xee, 0xc7, 0x0c, 0xc9, 0x4e, 0x9b, 0x75,
	0x83, 0x3d, 0xf9, 0x9e, 0xa3, 0x73, 0x8c, 0xee, 0x3d, 0x57, 0x70, 0x5e, 0xd6, 0xe9, 0x3e, 0x2b,
	0x84, 0x9f, 0x17, 0x59, 0x95, 0x61, 0x4b, 0x7f, 0x46, 0xaf, 0xf6, 0x59, 0xb6, 0x8f, 0xe5, 0xa5,
	0x46, 0xbb, 0xfa, 0xfe, 0xb2, 0x8a, 0x12, 0x59, 0x56, 0x22, 0xc9, 0x5b, 0xdd, 0xe8, 0xc5, 0x53,
	0x81, 0x48, 0x9b, 0xf6, 0xc8, 0x7b, 0x0d, 0x83, 0x8d, 0x2c, 0x2b, 0x2e, 0x7f, 0xd6, 0xb2, 0xac,
	0x30, 0x06, 0x33, 0x15, 0x89, 0x24, 0x88, 0x22, 0xe6, 0x70, 0x5d, 0x7b, 0xbf, 0x0c, 0x70, 0x5a,
	0x4d, 0x1e, 0x37, 0x98, 0x40, 0x3f, 0x91, 0x65, 0x29, 0xf6, 0x07, 0xd1, 0x01, 0x2a, 0xef, 0x5d,
	0x5a, 0x7d, 0x20, 0x3d, 0x8a, 0x98, 0xc1, 0x75, 0xdd, 0x71, 0x01, 0x31, 0x28, 0x62, 0xa6, 0xe6,
	0x82, 0x8e, 0x1b, 0x13, 0x93, 0x22, 0x66, 0x69, 0x6e, 0xdc, 0x71, 0x13, 0x62, 0x51, 0xc4, 0xce,
	0x35, 0x37, 0x51, 0xdc, 0x7d, 0x2c, 0xf6, 0xc4, 0xa6, 0x88, 0x9d, 0x72, 0x5d, 0xe3, 0x0b, 0xb0,
	0xf2, 0x22, 0xba, 0x93, 0xa4, 0x4f, 0x11, 0xeb, 0xf1, 0x16, 0x28, 0xb6, 0xac, 0x93, 0x44, 0x90,
	0x53, 0x8a, 0x18, 0xe2, 0x2d, 0x50, 0xfe, 0x50, 0x54, 0x82, 0x38, 0x14, 0xb1, 0x33, 0xae, 0x6b,
	0xfc, 0x11, 0xec, 0xb2, 0x12, 0x55, 0x5d, 0x12, 0xa0, 0x88, 0x0d, 0x83, 0x97, 0xed, 0x18, 0xfc,
	0x87, 0xfe, 0xfc, 0xb5, 0x3e, 0x5e, 0x15, 0xa1, 0x2c, 0x4a, 0xde, 0x89, 0x31, 0x03, 0x2b, 0xff,
	0x91, 0xa5, 0x92, 0x0c, 0xa8, 0xc1, 0x06, 0x01, 0xee, 0x5c, 0xb7, 0x8a, 0x5b, 0xd6, 0xc9, 0x4e,
	0x16, 0xbc, 0x15, 0xe0, 0x19, 0x3c, 0x13, 0x61, 0x18, 0x55, 0x51, 0x96, 0x8a, 0xf8, 0xbb, 0x0a,
	0x82, 0x9c, 0x51, 0xc4, 0x06, 0xc1, 0xc8, 0x6f, 0x43, 0xf0, 0x0f, 0x21, 0xf8, 0x9b, 0x43, 0x4a,
	0x7c, 0xf8, 0x68, 0x51, 0x24, 0x7e, 0x0b, 0x86, 0x48, 0x1b, 0x72, 0xae, 0x8d, 0x17, 0x7f, 0x19,
	0xa7, 0x69, 0xc3, 0x95, 0xc0, 0x9b, 0xc1, 0xd9, 0xf1, 0x75, 0xb1, 0x03, 0xd6, 0x17, 0x3e, 0xfd,
	0xba, 0x71, 0x4f, 0x70, 0x1f, 0x8c, 0xe5, 0x7c, 0xeb, 0x22, 0x7c, 0x0a, 0xe6, 0x76, 0xc5, 0xaf,
	0xdd, 0x1e, 0x06, 0xb0, 0x67, 0xd3, 0xe5, 0x6c, 0xbe, 0x70, 0x0d, 0xa5, 0x9c, 0x2d, 0x56, 0xeb,
	0xb9, 0x6b, 0x7a, 0xd7, 0x30, 0x38, 0xea, 0x03, 0x3f, 0x07, 0x3b, 0xd5, 0x55, 0x17, 0x6f, 0x87,
	0xf0, 0x1b, 0x30, 0xab, 0x26, 0x97, 0x3a, 0xdd, 0x61, 0xe0, 0x1e, 0x4f, 0x60, 0xd3, 0xe4, 0x92,
	0xeb, 0x53, 0x2f, 0x06, 0xfb, 0x56, 0x16, 0x65, 0x96, 0xfe, 0x6b, 0x93, 0xf0, 0x10, 0x7a, 0x51,
	0xa8, 0xff, 0x60, 0xf1, 0x5e, 0x14, 0xaa, 0xdc, 0x64, 0x22, 0xa2, 0x58, 0xaf, 0x87, 0xc3, 0x5b,
	0xf0, 0x38, 0x6c, 0xf3, 0x3f, 0xc3, 0x7e, 0xf7, 0x1e, 0x9c, 0x87, 0x0b, 0xa8, 0xf6, 0x6e, 0x56,
	0x9f, 0xbf, 0x2d, 0xe6, 0xee, 0x89, 0x6a, 0xfa, 0x6a, 0x75, 0x33, 0x3f, 0x6e, 0x3f, 0xf8, 0x04,
	0xfd, 0x75, 0xfb, 0x7a, 0xf0, 0x04, 0xe0, 0x4a, 0xc6, 0x71, 0xb6, 0xcd, 0x8a, 0x38, 0xc4, 0xf8,
	0x8f, 0x1d, 0xd0, 0xef, 0x60, 0xe4, 0x3e, 0xdd, 0x0b, 0xef, 0x64, 0x67, 0x6b, 0x6a, 0xfc, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0x6d, 0x3b, 0x72, 0x9c, 0x85, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SungoraClient is the client API for Sungora service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SungoraClient interface {
	HelloWorld(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error)
}

type sungoraClient struct {
	cc grpc.ClientConnInterface
}

func NewSungoraClient(cc grpc.ClientConnInterface) SungoraClient {
	return &sungoraClient{cc}
}

func (c *sungoraClient) HelloWorld(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error) {
	out := new(TestReply)
	err := c.cc.Invoke(ctx, "/proto.Sungora/HelloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SungoraServer is the server API for Sungora service.
type SungoraServer interface {
	HelloWorld(context.Context, *TestRequest) (*TestReply, error)
}

// UnimplementedSungoraServer can be embedded to have forward compatible implementations.
type UnimplementedSungoraServer struct {
}

func (*UnimplementedSungoraServer) HelloWorld(ctx context.Context, req *TestRequest) (*TestReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloWorld not implemented")
}

func RegisterSungoraServer(s *grpc.Server, srv SungoraServer) {
	s.RegisterService(&_Sungora_serviceDesc, srv)
}

func _Sungora_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SungoraServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sungora/HelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SungoraServer).HelloWorld(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sungora_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Sungora",
	HandlerType: (*SungoraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloWorld",
			Handler:    _Sungora_HelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sungora.proto",
}
