// Code generated by protoc-gen-go. DO NOT EDIT.
// source: modelcore.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Test struct {
	Text                 string               `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbebe0747f03f9f, []int{0}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Test) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Login                string               `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	IsOnline             bool                 `protobuf:"varint,4,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	SampleJs             []byte               `protobuf:"bytes,5,opt,name=sample_js,json=sampleJs,proto3" json:"sample_js,omitempty"`
	Price                string               `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Summa                float64              `protobuf:"fixed64,7,opt,name=summa,proto3" json:"summa,omitempty"`
	Cnt                  int64                `protobuf:"varint,8,opt,name=cnt,proto3" json:"cnt,omitempty"`
	Message              string               `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	NullJson             []byte               `protobuf:"bytes,10,opt,name=null_json,json=nullJson,proto3" json:"null_json,omitempty"`
	Butes                []byte               `protobuf:"bytes,11,opt,name=butes,proto3" json:"butes,omitempty"`
	SliceString          []string             `protobuf:"bytes,12,rep,name=slice_string,json=sliceString,proto3" json:"slice_string,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbebe0747f03f9f, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

func (m *User) GetSampleJs() []byte {
	if m != nil {
		return m.SampleJs
	}
	return nil
}

func (m *User) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *User) GetSumma() float64 {
	if m != nil {
		return m.Summa
	}
	return 0
}

func (m *User) GetCnt() int64 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

func (m *User) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *User) GetNullJson() []byte {
	if m != nil {
		return m.NullJson
	}
	return nil
}

func (m *User) GetButes() []byte {
	if m != nil {
		return m.Butes
	}
	return nil
}

func (m *User) GetSliceString() []string {
	if m != nil {
		return m.SliceString
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type Order struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Number               int64                `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Status               string               `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbebe0747f03f9f, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Order) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Order) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Order) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type Role struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbebe0747f03f9f, []int{3}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Role) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Test)(nil), "pb.Test")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*Order)(nil), "pb.Order")
	proto.RegisterType((*Role)(nil), "pb.Role")
}

func init() { proto.RegisterFile("modelcore.proto", fileDescriptor_cbbebe0747f03f9f) }

var fileDescriptor_cbbebe0747f03f9f = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4f, 0x6b, 0xdc, 0x3e,
	0x10, 0xfd, 0x79, 0xed, 0xfd, 0xe3, 0xd9, 0xfd, 0x25, 0x45, 0x94, 0x54, 0x6c, 0x0e, 0x75, 0xf7,
	0x64, 0x7a, 0x70, 0x20, 0x3d, 0x94, 0x1e, 0x73, 0xe8, 0xa1, 0xa1, 0x25, 0x45, 0x4d, 0xce, 0xc6,
	0xb6, 0xa6, 0x8b, 0x82, 0x6c, 0x19, 0x8f, 0x0c, 0xed, 0xc7, 0xe8, 0xe7, 0xeb, 0x97, 0x29, 0x92,
	0xbc, 0x50, 0x36, 0x85, 0x90, 0xdc, 0xf4, 0xde, 0xcc, 0x7b, 0xb2, 0xdf, 0x68, 0xe0, 0xb4, 0x35,
	0x12, 0x75, 0x63, 0x06, 0x2c, 0xfa, 0xc1, 0x58, 0xc3, 0x66, 0x7d, 0xbd, 0x7d, 0xbd, 0x37, 0x66,
	0xaf, 0xf1, 0xc2, 0x33, 0xf5, 0xf8, 0xfd, 0xc2, 0xaa, 0x16, 0xc9, 0x56, 0x6d, 0x1f, 0x9a, 0xb6,
	0xe7, 0xc7, 0x0d, 0xd8, 0xf6, 0xf6, 0x67, 0x28, 0xee, 0xee, 0x20, 0xb9, 0x45, 0xb2, 0x8c, 0x41,
	0x62, 0xf1, 0x87, 0xe5, 0x51, 0x16, 0xe5, 0xa9, 0xf0, 0x67, 0xf6, 0x01, 0xa0, 0x19, 0xb0, 0xb2,
	0x28, 0xcb, 0xca, 0xf2, 0x59, 0x16, 0xe5, 0xeb, 0xcb, 0x6d, 0x11, 0xdc, 0x8a, 0x83, 0x5b, 0x71,
	0x7b, 0xb8, 0x4e, 0xa4, 0x53, 0xf7, 0x95, 0xdd, 0xfd, 0x8e, 0x21, 0xb9, 0x23, 0x1c, 0xd8, 0x09,
	0xcc, 0x94, 0x9c, 0x5c, 0x67, 0x4a, 0xb2, 0x97, 0x30, 0xd7, 0x66, 0xaf, 0x3a, 0x6f, 0x97, 0x8a,
	0x00, 0x1c, 0x8b, 0x6d, 0xa5, 0x34, 0x8f, 0x03, 0xeb, 0x01, 0x3b, 0x87, 0x54, 0x51, 0x69, 0x3a,
	0xad, 0x3a, 0xe4, 0x49, 0x16, 0xe5, 0x2b, 0xb1, 0x52, 0x74, 0xe3, 0xb1, 0x2b, 0x52, 0xd5, 0xf6,
	0x1a, 0xcb, 0x7b, 0xe2, 0xf3, 0x2c, 0xca, 0x37, 0x62, 0x15, 0x88, 0x6b, 0x72, 0x7e, 0xfd, 0xa0,
	0x1a, 0xe4, 0x8b, 0xe0, 0xe7, 0x81, 0x63, 0x69, 0x6c, 0xdb, 0x8a, 0x2f, 0xb3, 0x28, 0x8f, 0x44,
	0x00, 0xec, 0x05, 0xc4, 0x4d, 0x67, 0xf9, 0x2a, 0x8b, 0xf2, 0x58, 0xb8, 0x23, 0xe3, 0xb0, 0x6c,
	0x91, 0xa8, 0xda, 0x23, 0x4f, 0xbd, 0xfe, 0x00, 0xdd, 0xa5, 0xdd, 0xa8, 0x75, 0x79, 0x4f, 0xa6,
	0xe3, 0x10, 0x2e, 0x75, 0xc4, 0x35, 0x19, 0xff, 0x13, 0xf5, 0x68, 0x91, 0xf8, 0xda, 0x17, 0x02,
	0x60, 0x6f, 0x60, 0x43, 0x5a, 0x35, 0x58, 0x92, 0x1d, 0x54, 0xb7, 0xe7, 0x9b, 0x2c, 0xce, 0x53,
	0xb1, 0xf6, 0xdc, 0x37, 0x4f, 0x1d, 0xe5, 0xfc, 0xff, 0x13, 0x72, 0x76, 0xd2, 0xb1, 0x97, 0x07,
	0xe9, 0xc9, 0xe3, 0xd2, 0xa9, 0x3b, 0x48, 0x25, 0x6a, 0x9c, 0xa4, 0xa7, 0x8f, 0x4b, 0xa7, 0xee,
	0x2b, 0xbb, 0xfb, 0x35, 0x83, 0xf9, 0xcd, 0x20, 0xff, 0x31, 0xde, 0x57, 0xb0, 0x1c, 0x09, 0x87,
	0x52, 0xc9, 0x69, 0xc0, 0x0b, 0x07, 0x3f, 0x49, 0x76, 0x06, 0x8b, 0x6e, 0x6c, 0x6b, 0x1c, 0xfc,
	0x88, 0x63, 0x31, 0x21, 0xc7, 0x93, 0xad, 0xec, 0x48, 0x7e, 0xc0, 0xa9, 0x98, 0xd0, 0x51, 0x26,
	0xf3, 0xe7, 0x67, 0xb2, 0x78, 0x7e, 0x26, 0xcb, 0xa7, 0x64, 0xf2, 0x19, 0x12, 0x61, 0x34, 0x3e,
	0x48, 0x84, 0x41, 0xd2, 0x18, 0x89, 0x53, 0x1c, 0xfe, 0xcc, 0x32, 0x58, 0x4b, 0xa4, 0x66, 0x50,
	0xbd, 0x55, 0xa6, 0x9b, 0x1e, 0xfd, 0xdf, 0xd4, 0xe5, 0x7b, 0x48, 0xbf, 0x1c, 0x76, 0x9d, 0xbd,
	0x85, 0xe4, 0xab, 0x7b, 0x27, 0x67, 0x0f, 0xbe, 0xe4, 0xa3, 0xdb, 0xe4, 0xed, 0xaa, 0xe8, 0xeb,
	0xc2, 0x6d, 0xf1, 0xee, 0xbf, 0x7a, 0xe1, 0x6b, 0xef, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x44,
	0x9a, 0xb6, 0xa1, 0x2b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ModelcoreClient is the client API for Modelcore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModelcoreClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Test, error)
}

type modelcoreClient struct {
	cc grpc.ClientConnInterface
}

func NewModelcoreClient(cc grpc.ClientConnInterface) ModelcoreClient {
	return &modelcoreClient{cc}
}

func (c *modelcoreClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Test, error) {
	out := new(Test)
	err := c.cc.Invoke(ctx, "/pb.Modelcore/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelcoreServer is the server API for Modelcore service.
type ModelcoreServer interface {
	Ping(context.Context, *empty.Empty) (*Test, error)
}

// UnimplementedModelcoreServer can be embedded to have forward compatible implementations.
type UnimplementedModelcoreServer struct {
}

func (*UnimplementedModelcoreServer) Ping(ctx context.Context, req *empty.Empty) (*Test, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterModelcoreServer(s *grpc.Server, srv ModelcoreServer) {
	s.RegisterService(&_Modelcore_serviceDesc, srv)
}

func _Modelcore_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelcoreServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Modelcore/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelcoreServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Modelcore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Modelcore",
	HandlerType: (*ModelcoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Modelcore_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modelcore.proto",
}
