// Code generated by protoc-gen-go. DO NOT EDIT.
// source: modelsun.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Test struct {
	Text                 string               `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d7702773df53470, []int{0}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Test) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Login                string               `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Price                string               `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	SummaOne             float32              `protobuf:"fixed32,5,opt,name=summa_one,json=summaOne,proto3" json:"summa_one,omitempty"`
	SummaTwo             float64              `protobuf:"fixed64,6,opt,name=summa_two,json=summaTwo,proto3" json:"summa_two,omitempty"`
	Cnt2                 int32                `protobuf:"varint,7,opt,name=cnt2,proto3" json:"cnt2,omitempty"`
	Cnt4                 int64                `protobuf:"varint,8,opt,name=cnt4,proto3" json:"cnt4,omitempty"`
	Cnt8                 int64                `protobuf:"varint,9,opt,name=cnt8,proto3" json:"cnt8,omitempty"`
	IsOnline             bool                 `protobuf:"varint,10,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	Alias                []string             `protobuf:"bytes,11,rep,name=alias,proto3" json:"alias,omitempty"`
	DataByte             []byte               `protobuf:"bytes,12,opt,name=data_byte,json=dataByte,proto3" json:"data_byte,omitempty"`
	Metrika              []byte               `protobuf:"bytes,13,opt,name=metrika,proto3" json:"metrika,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,16,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d7702773df53470, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *User) GetSummaOne() float32 {
	if m != nil {
		return m.SummaOne
	}
	return 0
}

func (m *User) GetSummaTwo() float64 {
	if m != nil {
		return m.SummaTwo
	}
	return 0
}

func (m *User) GetCnt2() int32 {
	if m != nil {
		return m.Cnt2
	}
	return 0
}

func (m *User) GetCnt4() int64 {
	if m != nil {
		return m.Cnt4
	}
	return 0
}

func (m *User) GetCnt8() int64 {
	if m != nil {
		return m.Cnt8
	}
	return 0
}

func (m *User) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

func (m *User) GetAlias() []string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *User) GetDataByte() []byte {
	if m != nil {
		return m.DataByte
	}
	return nil
}

func (m *User) GetMetrika() []byte {
	if m != nil {
		return m.Metrika
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type Order struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Number               int64                `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Status               int32                `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d7702773df53470, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Order) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Order) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Order) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Order) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Order) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type Role struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d7702773df53470, []int{3}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Role) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Test)(nil), "pb.Test")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*Order)(nil), "pb.Order")
	proto.RegisterType((*Role)(nil), "pb.Role")
}

func init() { proto.RegisterFile("modelsun.proto", fileDescriptor_6d7702773df53470) }

var fileDescriptor_6d7702773df53470 = []byte{
	// 505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xd1, 0x6a, 0xdb, 0x3e,
	0x14, 0xc6, 0x6b, 0xc7, 0x8e, 0x1d, 0xa5, 0xff, 0xfc, 0x87, 0x18, 0x9d, 0x48, 0x2f, 0x6a, 0x72,
	0x65, 0x76, 0xe1, 0x42, 0xd6, 0x8b, 0xee, 0xb2, 0x83, 0x31, 0x06, 0x83, 0x0c, 0x2f, 0xdd, 0x6d,
	0x90, 0xa3, 0xb3, 0x20, 0x66, 0x4b, 0xc6, 0x3a, 0xa6, 0xcb, 0x63, 0xec, 0x31, 0xf7, 0x16, 0x43,
	0xb2, 0x52, 0x4a, 0x3a, 0x28, 0xed, 0x9d, 0xbe, 0x9f, 0xce, 0x77, 0xa2, 0x7c, 0xc7, 0x87, 0xcc,
	0x1a, 0x2d, 0xa0, 0x36, 0xbd, 0x2a, 0xda, 0x4e, 0xa3, 0xa6, 0x61, 0x5b, 0xcd, 0x2f, 0x76, 0x5a,
	0xef, 0x6a, 0xb8, 0x74, 0xa4, 0xea, 0x7f, 0x5c, 0xa2, 0x6c, 0xc0, 0x20, 0x6f, 0xda, 0xa1, 0x68,
	0x7e, 0x7e, 0x5c, 0x00, 0x4d, 0x8b, 0xfb, 0xe1, 0x72, 0x71, 0x4b, 0xa2, 0x35, 0x18, 0xa4, 0x94,
	0x44, 0x08, 0xbf, 0x90, 0x05, 0x59, 0x90, 0x4f, 0x4a, 0x77, 0xa6, 0xef, 0x09, 0xd9, 0x76, 0xc0,
	0x11, 0xc4, 0x86, 0x23, 0x0b, 0xb3, 0x20, 0x9f, 0x2e, 0xe7, 0xc5, 0xd0, 0xad, 0x38, 0x74, 0x2b,
	0xd6, 0x87, 0x9f, 0x2b, 0x27, 0xbe, 0xfa, 0x06, 0x17, 0x7f, 0x46, 0x24, 0xba, 0x35, 0xd0, 0xd1,
	0x19, 0x09, 0xa5, 0xf0, 0x5d, 0x43, 0x29, 0xe8, 0x6b, 0x12, 0xd7, 0x7a, 0x27, 0x95, 0x6b, 0x37,
	0x29, 0x07, 0x61, 0x29, 0x34, 0x5c, 0xd6, 0x6c, 0x34, 0x50, 0x27, 0x2c, 0x6d, 0x3b, 0xb9, 0x05,
	0x16, 0x0d, 0xd4, 0x09, 0x7a, 0x4e, 0x26, 0xa6, 0x6f, 0x1a, 0xbe, 0xd1, 0x0a, 0x58, 0x9c, 0x05,
	0x79, 0x58, 0xa6, 0x0e, 0xac, 0xd4, 0x83, 0x4b, 0xbc, 0xd3, 0x6c, 0x9c, 0x05, 0x79, 0xe0, 0x2f,
	0xd7, 0x77, 0xda, 0xfe, 0xc7, 0xad, 0xc2, 0x25, 0x4b, 0xb2, 0x20, 0x8f, 0x4b, 0x77, 0xf6, 0xec,
	0x8a, 0xa5, 0x59, 0x90, 0x8f, 0x1c, 0xbb, 0xf2, 0xec, 0x9a, 0x4d, 0xee, 0xd9, 0xb5, 0x6d, 0x2c,
	0xcd, 0x46, 0xab, 0x5a, 0x2a, 0x60, 0x24, 0x0b, 0xf2, 0xb4, 0x4c, 0xa5, 0x59, 0x39, 0x6d, 0x1f,
	0xca, 0x6b, 0xc9, 0x0d, 0x9b, 0x66, 0x23, 0xfb, 0x50, 0x27, 0xac, 0x45, 0x70, 0xe4, 0x9b, 0x6a,
	0x8f, 0xc0, 0x4e, 0xb3, 0x20, 0x3f, 0x2d, 0x53, 0x0b, 0x3e, 0xec, 0x11, 0x28, 0x23, 0x49, 0x03,
	0xd8, 0xc9, 0x9f, 0x9c, 0xfd, 0xe7, 0xae, 0x0e, 0xf2, 0x28, 0xf5, 0xd9, 0x33, 0x52, 0xb7, 0xd6,
	0xbe, 0x15, 0x07, 0xeb, 0xff, 0x4f, 0x5b, 0x7d, 0xf5, 0x60, 0x15, 0x50, 0x83, 0xb7, 0xbe, 0x7a,
	0xda, 0xea, 0xab, 0x6f, 0x70, 0xf1, 0x3b, 0x24, 0xf1, 0xaa, 0x13, 0xff, 0x18, 0xf6, 0x1b, 0x92,
	0xf4, 0x06, 0xba, 0x8d, 0x14, 0x7e, 0xdc, 0x63, 0x2b, 0x3f, 0x0b, 0x7a, 0x46, 0xc6, 0xaa, 0x6f,
	0x2a, 0xe8, 0xdc, 0xc0, 0x47, 0xa5, 0x57, 0x96, 0x1b, 0xe4, 0xd8, 0x1b, 0x37, 0xf2, 0xb8, 0xf4,
	0xea, 0x28, 0x93, 0xf8, 0xe5, 0x99, 0x8c, 0x5f, 0x9e, 0x49, 0xf2, 0x9c, 0x4c, 0xbe, 0x90, 0xa8,
	0xd4, 0x35, 0x3c, 0x4a, 0xc4, 0x7e, 0x5a, 0x5a, 0x80, 0x8f, 0xc3, 0x9d, 0x69, 0x46, 0xa6, 0x02,
	0xcc, 0xb6, 0x93, 0x2d, 0x4a, 0xad, 0xfc, 0x0a, 0x3c, 0x44, 0xcb, 0xef, 0x24, 0xf9, 0xd6, 0xab,
	0x9d, 0xee, 0x38, 0x7d, 0x4b, 0xa2, 0xaf, 0x52, 0xed, 0xe8, 0xd9, 0xa3, 0x77, 0x7c, 0xb4, 0x5b,
	0x3d, 0x4f, 0x8b, 0xb6, 0x2a, 0xec, 0x46, 0x2f, 0x4e, 0xe8, 0x05, 0x49, 0x3e, 0x01, 0xba, 0x35,
	0xbc, 0xc7, 0x43, 0x81, 0x65, 0x8b, 0x93, 0x6a, 0xec, 0xcc, 0xef, 0xfe, 0x06, 0x00, 0x00, 0xff,
	0xff, 0xcf, 0x34, 0x89, 0x5c, 0x57, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SungoraClient is the client API for Sungora service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SungoraClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Test, error)
	GetUser(ctx context.Context, in *Test, opts ...grpc.CallOption) (*User, error)
}

type sungoraClient struct {
	cc grpc.ClientConnInterface
}

func NewSungoraClient(cc grpc.ClientConnInterface) SungoraClient {
	return &sungoraClient{cc}
}

func (c *sungoraClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Test, error) {
	out := new(Test)
	err := c.cc.Invoke(ctx, "/pb.Sungora/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sungoraClient) GetUser(ctx context.Context, in *Test, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/pb.Sungora/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SungoraServer is the server API for Sungora service.
type SungoraServer interface {
	Ping(context.Context, *empty.Empty) (*Test, error)
	GetUser(context.Context, *Test) (*User, error)
}

// UnimplementedSungoraServer can be embedded to have forward compatible implementations.
type UnimplementedSungoraServer struct {
}

func (*UnimplementedSungoraServer) Ping(ctx context.Context, req *empty.Empty) (*Test, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedSungoraServer) GetUser(ctx context.Context, req *Test) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterSungoraServer(s *grpc.Server, srv SungoraServer) {
	s.RegisterService(&_Sungora_serviceDesc, srv)
}

func _Sungora_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SungoraServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sungora/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SungoraServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sungora_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Test)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SungoraServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sungora/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SungoraServer).GetUser(ctx, req.(*Test))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sungora_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Sungora",
	HandlerType: (*SungoraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Sungora_Ping_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Sungora_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modelsun.proto",
}
