// Code generated by protoc-gen-go. DO NOT EDIT.
// source: modelcore.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Test struct {
	MESSAGe              string   `protobuf:"bytes,1,opt,name=m_e_s_s_a_ge,json=mESSAGe,proto3" json:"m_e_s_s_a_ge,omitempty"`
	MeSsIge              string   `protobuf:"bytes,2,opt,name=me_ss_ige,json=meSsIge,proto3" json:"me_ss_ige,omitempty"`
	Ddd                  float32  `protobuf:"fixed32,3,opt,name=ddd,proto3" json:"ddd,omitempty"`
	Fsdf                 float64  `protobuf:"fixed64,4,opt,name=fsdf,proto3" json:"fsdf,omitempty"`
	Fsdfdsfdf            int64    `protobuf:"varint,5,opt,name=fsdfdsfdf,proto3" json:"fsdfdsfdf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbebe0747f03f9f, []int{0}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetMESSAGe() string {
	if m != nil {
		return m.MESSAGe
	}
	return ""
}

func (m *Test) GetMeSsIge() string {
	if m != nil {
		return m.MeSsIge
	}
	return ""
}

func (m *Test) GetDdd() float32 {
	if m != nil {
		return m.Ddd
	}
	return 0
}

func (m *Test) GetFsdf() float64 {
	if m != nil {
		return m.Fsdf
	}
	return 0
}

func (m *Test) GetFsdfdsfdf() int64 {
	if m != nil {
		return m.Fsdfdsfdf
	}
	return 0
}

type User struct {
	Asdf                 []string             `protobuf:"bytes,1,rep,name=asdf,proto3" json:"asdf,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Login                string               `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	IsOnline             bool                 `protobuf:"varint,5,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	SampleJs             *any.Any             `protobuf:"bytes,6,opt,name=sample_js,json=sampleJs,proto3" json:"sample_js,omitempty"`
	Price                string               `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	Summa                float64              `protobuf:"fixed64,8,opt,name=summa,proto3" json:"summa,omitempty"`
	Cnt                  int64                `protobuf:"varint,9,opt,name=cnt,proto3" json:"cnt,omitempty"`
	Message              string               `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,13,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbebe0747f03f9f, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetAsdf() []string {
	if m != nil {
		return m.Asdf
	}
	return nil
}

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

func (m *User) GetSampleJs() *any.Any {
	if m != nil {
		return m.SampleJs
	}
	return nil
}

func (m *User) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *User) GetSumma() float64 {
	if m != nil {
		return m.Summa
	}
	return 0
}

func (m *User) GetCnt() int64 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

func (m *User) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type Order struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Number               int64                `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Status               string               `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbebe0747f03f9f, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Order) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Order) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Order) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type Role struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbebe0747f03f9f, []int{3}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Role) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Test)(nil), "pb.Test")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*Order)(nil), "pb.Order")
	proto.RegisterType((*Role)(nil), "pb.Role")
}

func init() { proto.RegisterFile("modelcore.proto", fileDescriptor_cbbebe0747f03f9f) }

var fileDescriptor_cbbebe0747f03f9f = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x25, 0xbb, 0xd9, 0xec, 0x66, 0x5a, 0x3e, 0x64, 0x55, 0xc5, 0x6c, 0x41, 0x44, 0x7b, 0xca,
	0x69, 0x2b, 0xca, 0x89, 0x0b, 0xd2, 0x1e, 0x2a, 0x5a, 0x84, 0x54, 0xe1, 0x16, 0x71, 0x8c, 0xb2,
	0xf1, 0x6c, 0x64, 0x14, 0xc7, 0x91, 0xed, 0x08, 0xf5, 0x07, 0xf0, 0x03, 0xf8, 0x25, 0xfc, 0x45,
	0x64, 0xc7, 0x29, 0xa8, 0x15, 0xaa, 0xe8, 0x29, 0xf3, 0xde, 0xcc, 0xd3, 0xd8, 0xef, 0xc5, 0xf0,
	0x54, 0x2a, 0x8e, 0x4d, 0xa5, 0x34, 0xae, 0x3b, 0xad, 0xac, 0x22, 0x93, 0x6e, 0xbb, 0x7c, 0x5d,
	0x2b, 0x55, 0x37, 0x78, 0xec, 0x99, 0x6d, 0xbf, 0x3b, 0xb6, 0x42, 0xa2, 0xb1, 0xa5, 0xec, 0x86,
	0xa1, 0xe5, 0x8b, 0xdb, 0x03, 0x65, 0x7b, 0x1d, 0x5a, 0x47, 0xb7, 0x5b, 0x28, 0x3b, 0x1b, 0x9a,
	0xab, 0x1f, 0x11, 0xc4, 0x57, 0x68, 0x2c, 0x79, 0x05, 0xfb, 0xb2, 0xc0, 0xc2, 0x14, 0xa6, 0x28,
	0x8b, 0x1a, 0x69, 0x94, 0x45, 0x79, 0xca, 0xe6, 0xf2, 0xf4, 0xf2, 0x72, 0xf3, 0x01, 0xc9, 0x12,
	0x52, 0x89, 0x85, 0x31, 0x85, 0xa8, 0x91, 0x4e, 0x42, 0x0f, 0x2f, 0xcd, 0x79, 0x8d, 0xe4, 0x19,
	0x4c, 0x39, 0xe7, 0x74, 0x9a, 0x45, 0xf9, 0x84, 0xb9, 0x92, 0x10, 0x88, 0x77, 0x86, 0xef, 0x68,
	0x9c, 0x45, 0x79, 0xc4, 0x7c, 0x4d, 0x5e, 0x42, 0xea, 0xbe, 0xdc, 0xec, 0xf8, 0x8e, 0xce, 0xb2,
	0x28, 0x9f, 0xb2, 0x3f, 0xc4, 0xea, 0xd7, 0x14, 0xe2, 0x2f, 0x06, 0xb5, 0x93, 0x96, 0x4e, 0x1a,
	0x65, 0xd3, 0x3c, 0x65, 0xbe, 0x26, 0x4f, 0x60, 0x22, 0x78, 0xd8, 0x3a, 0x11, 0x9c, 0x1c, 0xc0,
	0xac, 0x51, 0xb5, 0x68, 0xfd, 0xca, 0x94, 0x0d, 0xc0, 0xb1, 0x28, 0x4b, 0xd1, 0xf8, 0xad, 0x29,
	0x1b, 0x00, 0x39, 0x82, 0x54, 0x98, 0x42, 0xb5, 0x8d, 0x68, 0xd1, 0xaf, 0x5d, 0xb0, 0x85, 0x30,
	0x17, 0x1e, 0x93, 0x37, 0x90, 0x9a, 0x52, 0x76, 0x0d, 0x16, 0xdf, 0x0c, 0x4d, 0xb2, 0x28, 0xdf,
	0x3b, 0x39, 0x58, 0x0f, 0x76, 0xad, 0x47, 0xbb, 0xd6, 0x9b, 0xf6, 0x9a, 0x2d, 0x86, 0xb1, 0x8f,
	0xc6, 0x6d, 0xe9, 0xb4, 0xa8, 0x90, 0xce, 0x87, 0x2d, 0x1e, 0x38, 0xd6, 0xf4, 0x52, 0x96, 0x74,
	0xe1, 0x6f, 0x3c, 0x00, 0x67, 0x4c, 0xd5, 0x5a, 0x9a, 0xfa, 0xcb, 0xba, 0x92, 0x50, 0x98, 0x4b,
	0x34, 0xa6, 0xac, 0x91, 0xc2, 0x68, 0xa2, 0x87, 0xe4, 0x1d, 0x40, 0xa5, 0xb1, 0xb4, 0xc8, 0x8b,
	0xd2, 0xd2, 0x3d, 0x7f, 0x96, 0xe5, 0x9d, 0xb3, 0x5c, 0x8d, 0xb1, 0xb3, 0x34, 0x4c, 0x6f, 0xac,
	0x93, 0xf6, 0x1d, 0x1f, 0xa5, 0xfb, 0xf7, 0x4b, 0xc3, 0xf4, 0x20, 0xe5, 0xd8, 0x60, 0x90, 0x3e,
	0xbe, 0x5f, 0x1a, 0xa6, 0x37, 0x76, 0xf5, 0x73, 0x02, 0xb3, 0x0b, 0xcd, 0x51, 0x87, 0x78, 0xa2,
	0x9b, 0x78, 0x9e, 0xc3, 0xbc, 0x37, 0xa8, 0x8b, 0x9b, 0xcc, 0x12, 0x07, 0xcf, 0x39, 0x39, 0x84,
	0xa4, 0xed, 0xe5, 0x16, 0xb5, 0x0f, 0x6e, 0xca, 0x02, 0x72, 0xbc, 0xb1, 0xa5, 0xed, 0x4d, 0x88,
	0x2e, 0xa0, 0x5b, 0x9e, 0xcc, 0x1e, 0xee, 0x49, 0xf2, 0x70, 0x4f, 0xe6, 0xff, 0xe3, 0xc9, 0x27,
	0x88, 0x99, 0x6a, 0xf0, 0x8e, 0x23, 0x04, 0xe2, 0x4a, 0xf1, 0xf1, 0xe1, 0xf8, 0x9a, 0x64, 0xb0,
	0xc7, 0xd1, 0x54, 0x5a, 0x74, 0x56, 0xa8, 0xf1, 0x57, 0xfe, 0x9b, 0x3a, 0x39, 0x83, 0xe4, 0xf3,
	0x77, 0xd4, 0xf6, 0x9a, 0xbc, 0x07, 0x38, 0xc3, 0xa6, 0x51, 0x5f, 0x95, 0x6e, 0x38, 0x39, 0xbc,
	0x73, 0x98, 0x53, 0xf7, 0xa2, 0x97, 0xff, 0xe0, 0x57, 0x8f, 0xb6, 0x89, 0x67, 0xde, 0xfe, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x6d, 0x1b, 0x65, 0xca, 0x5c, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// QwertyClient is the client API for Qwerty service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QwertyClient interface {
	HelloWorld(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type qwertyClient struct {
	cc grpc.ClientConnInterface
}

func NewQwertyClient(cc grpc.ClientConnInterface) QwertyClient {
	return &qwertyClient{cc}
}

func (c *qwertyClient) HelloWorld(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.Qwerty/HelloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QwertyServer is the server API for Qwerty service.
type QwertyServer interface {
	HelloWorld(context.Context, *empty.Empty) (*empty.Empty, error)
}

// UnimplementedQwertyServer can be embedded to have forward compatible implementations.
type UnimplementedQwertyServer struct {
}

func (*UnimplementedQwertyServer) HelloWorld(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloWorld not implemented")
}

func RegisterQwertyServer(s *grpc.Server, srv QwertyServer) {
	s.RegisterService(&_Qwerty_serviceDesc, srv)
}

func _Qwerty_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QwertyServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Qwerty/HelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QwertyServer).HelloWorld(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Qwerty_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Qwerty",
	HandlerType: (*QwertyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloWorld",
			Handler:    _Qwerty_HelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modelcore.proto",
}
