// Code generated by protoc-gen-go. DO NOT EDIT.
// source: modelsun.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Test struct {
	Text                 string               `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d7702773df53470, []int{0}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Test) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Login                string               `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	IsOnline             bool                 `protobuf:"varint,4,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	Price                string               `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Summa                float64              `protobuf:"fixed64,7,opt,name=summa,proto3" json:"summa,omitempty"`
	Cnt                  int64                `protobuf:"varint,8,opt,name=cnt,proto3" json:"cnt,omitempty"`
	Message              string               `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	Metrika              []byte               `protobuf:"bytes,10,opt,name=metrika,proto3" json:"metrika,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d7702773df53470, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

func (m *User) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *User) GetSumma() float64 {
	if m != nil {
		return m.Summa
	}
	return 0
}

func (m *User) GetCnt() int64 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

func (m *User) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *User) GetMetrika() []byte {
	if m != nil {
		return m.Metrika
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type Order struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Number               int64                `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Status               int32                `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d7702773df53470, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Order) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Order) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Order) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Order) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Order) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type Role struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d7702773df53470, []int{3}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Role) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Test)(nil), "pb.Test")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*Order)(nil), "pb.Order")
	proto.RegisterType((*Role)(nil), "pb.Role")
}

func init() { proto.RegisterFile("modelsun.proto", fileDescriptor_6d7702773df53470) }

var fileDescriptor_6d7702773df53470 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x8b, 0xd4, 0x40,
	0x10, 0x35, 0x1f, 0x93, 0x49, 0x6a, 0x75, 0x94, 0x46, 0xd6, 0x66, 0xf6, 0x60, 0x98, 0x53, 0xf0,
	0x90, 0x85, 0x15, 0x04, 0x8f, 0x7b, 0xf0, 0x20, 0x28, 0x2b, 0xcd, 0xee, 0x79, 0x48, 0xd2, 0x65,
	0x68, 0x4c, 0xd2, 0xa1, 0xbb, 0x03, 0x7a, 0xf5, 0x1f, 0xf8, 0x8f, 0xa5, 0x3f, 0x02, 0x32, 0x2b,
	0x2c, 0xbb, 0xb7, 0x7a, 0xaf, 0xde, 0xab, 0x84, 0x57, 0x5d, 0xb0, 0x1b, 0x25, 0xc7, 0x41, 0x2f,
	0x53, 0x3d, 0x2b, 0x69, 0x24, 0x89, 0xe7, 0x76, 0xff, 0xb6, 0x97, 0xb2, 0x1f, 0xf0, 0xd2, 0x31,
	0xed, 0xf2, 0xfd, 0xd2, 0x88, 0x11, 0xb5, 0x69, 0xc6, 0xd9, 0x8b, 0xf6, 0x17, 0xa7, 0x02, 0x1c,
	0x67, 0xf3, 0xcb, 0x37, 0x0f, 0x77, 0x90, 0xde, 0xa2, 0x36, 0x84, 0x40, 0x6a, 0xf0, 0xa7, 0xa1,
	0x51, 0x19, 0x55, 0x05, 0x73, 0x35, 0xf9, 0x08, 0xd0, 0x29, 0x6c, 0x0c, 0xf2, 0x63, 0x63, 0x68,
	0x5c, 0x46, 0xd5, 0xd9, 0xd5, 0xbe, 0xf6, 0xd3, 0xea, 0x75, 0x5a, 0x7d, 0xbb, 0x7e, 0x8e, 0x15,
	0x41, 0x7d, 0x6d, 0x0e, 0xbf, 0x13, 0x48, 0xef, 0x34, 0x2a, 0xb2, 0x83, 0x58, 0xf0, 0x30, 0x35,
	0x16, 0x9c, 0xbc, 0x86, 0xcd, 0x20, 0x7b, 0x31, 0xb9, 0x71, 0x05, 0xf3, 0xc0, 0xb2, 0x38, 0x36,
	0x62, 0xa0, 0x89, 0x67, 0x1d, 0x20, 0x17, 0x50, 0x08, 0x7d, 0x94, 0xd3, 0x20, 0x26, 0xa4, 0x69,
	0x19, 0x55, 0x39, 0xcb, 0x85, 0xbe, 0x71, 0xd8, 0x5a, 0x66, 0x25, 0x3a, 0xa4, 0x99, 0xb7, 0x38,
	0x60, 0x59, 0xbd, 0x8c, 0x63, 0x43, 0xb7, 0x65, 0x54, 0x45, 0xcc, 0x03, 0xf2, 0x0a, 0x92, 0x6e,
	0x32, 0x34, 0x2f, 0xa3, 0x2a, 0x61, 0xb6, 0x24, 0x14, 0xb6, 0x23, 0x6a, 0xdd, 0xf4, 0x48, 0x0b,
	0xe7, 0x5f, 0xa1, 0xef, 0x18, 0x25, 0x7e, 0x34, 0x14, 0xca, 0xa8, 0x7a, 0xce, 0x56, 0x78, 0x12,
	0xc7, 0x8b, 0x47, 0xc4, 0x61, 0xad, 0xcb, 0xcc, 0x57, 0xeb, 0xee, 0x61, 0x6b, 0x50, 0x7b, 0x2b,
	0xc7, 0x01, 0x83, 0xf5, 0xe5, 0xc3, 0xd6, 0xa0, 0xbe, 0x36, 0x87, 0x3f, 0x31, 0x6c, 0x6e, 0x14,
	0xff, 0xcf, 0x16, 0xde, 0xc0, 0x76, 0xd1, 0xa8, 0x8e, 0x82, 0x87, 0x3d, 0x64, 0x16, 0x7e, 0xe6,
	0xe4, 0x1c, 0xb2, 0x69, 0x19, 0x5b, 0x54, 0x6e, 0x13, 0x09, 0x0b, 0xc8, 0xf2, 0xda, 0x34, 0x66,
	0xd1, 0x6e, 0x0f, 0x1b, 0x16, 0xd0, 0x49, 0x26, 0x9b, 0xa7, 0x67, 0x92, 0x3d, 0x3d, 0x93, 0xed,
	0x63, 0x32, 0xf9, 0x02, 0x29, 0x93, 0x03, 0xde, 0x4b, 0x84, 0x40, 0xda, 0x49, 0x8e, 0x21, 0x0e,
	0x57, 0x93, 0x12, 0xce, 0x38, 0xea, 0x4e, 0x89, 0xd9, 0x08, 0x39, 0x85, 0xb7, 0xf9, 0x2f, 0x75,
	0xf5, 0x01, 0xf2, 0xaf, 0xe1, 0x22, 0xc9, 0x3b, 0x48, 0xbf, 0x89, 0xa9, 0x27, 0xe7, 0xf7, 0x7e,
	0xe4, 0x93, 0xbd, 0xb7, 0x7d, 0x5e, 0xcf, 0x6d, 0x6d, 0x6f, 0xed, 0xf0, 0xac, 0xcd, 0x5c, 0xef,
	0xfd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x62, 0x0d, 0x8a, 0xd0, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ModelsunClient is the client API for Modelsun service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModelsunClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Test, error)
}

type modelsunClient struct {
	cc grpc.ClientConnInterface
}

func NewModelsunClient(cc grpc.ClientConnInterface) ModelsunClient {
	return &modelsunClient{cc}
}

func (c *modelsunClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Test, error) {
	out := new(Test)
	err := c.cc.Invoke(ctx, "/pb.Modelsun/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelsunServer is the server API for Modelsun service.
type ModelsunServer interface {
	Ping(context.Context, *empty.Empty) (*Test, error)
}

// UnimplementedModelsunServer can be embedded to have forward compatible implementations.
type UnimplementedModelsunServer struct {
}

func (*UnimplementedModelsunServer) Ping(ctx context.Context, req *empty.Empty) (*Test, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterModelsunServer(s *grpc.Server, srv ModelsunServer) {
	s.RegisterService(&_Modelsun_serviceDesc, srv)
}

func _Modelsun_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelsunServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Modelsun/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelsunServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Modelsun_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Modelsun",
	HandlerType: (*ModelsunServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Modelsun_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modelsun.proto",
}
