// Code generated by protoc-gen-go. DO NOT EDIT.
// source: modelcore.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Test struct {
	MESSAGe              string   `protobuf:"bytes,1,opt,name=m_e_s_s_a_ge,json=mESSAGe,proto3" json:"m_e_s_s_a_ge,omitempty"`
	MeSsIge              string   `protobuf:"bytes,2,opt,name=me_ss_ige,json=meSsIge,proto3" json:"me_ss_ige,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbebe0747f03f9f, []int{0}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetMESSAGe() string {
	if m != nil {
		return m.MESSAGe
	}
	return ""
}

func (m *Test) GetMeSsIge() string {
	if m != nil {
		return m.MeSsIge
	}
	return ""
}

type Role struct {
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbebe0747f03f9f, []int{1}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Role) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Order struct {
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbebe0747f03f9f, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type User struct {
	Login                string   `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbbebe0747f03f9f, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*Test)(nil), "pb.Test")
	proto.RegisterType((*Role)(nil), "pb.Role")
	proto.RegisterType((*Order)(nil), "pb.Order")
	proto.RegisterType((*User)(nil), "pb.User")
}

func init() { proto.RegisterFile("modelcore.proto", fileDescriptor_cbbebe0747f03f9f) }

var fileDescriptor_cbbebe0747f03f9f = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcf, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xbf, 0xf6, 0x4b, 0x23, 0x1d, 0x05, 0x61, 0x90, 0x12, 0x22, 0x62, 0xc9, 0xc9, 0x53,
	0x0a, 0xf5, 0x2a, 0x42, 0x0f, 0xc5, 0x7a, 0x12, 0x1b, 0xc5, 0xe3, 0x92, 0x1f, 0xe3, 0x12, 0xd8,
	0x75, 0xc2, 0xce, 0x16, 0xe9, 0x7f, 0x2f, 0xdd, 0x24, 0xe0, 0xc5, 0xdb, 0xbe, 0xcf, 0xfb, 0xee,
	0x1c, 0x1e, 0xb8, 0xb4, 0xdc, 0x90, 0xa9, 0xd9, 0x51, 0xde, 0x39, 0xf6, 0x8c, 0xd3, 0xae, 0x4a,
	0xaf, 0x35, 0xb3, 0x36, 0xb4, 0x0a, 0xa4, 0x3a, 0x7c, 0xae, 0xc8, 0x76, 0xfe, 0xd8, 0x0f, 0xb2,
	0x0d, 0x44, 0x6f, 0x24, 0x1e, 0x6f, 0xe0, 0xc2, 0x2a, 0x52, 0xa2, 0x44, 0x95, 0x4a, 0x53, 0x32,
	0x59, 0x4e, 0xee, 0xe6, 0xfb, 0x33, 0xbb, 0x2d, 0x8a, 0xcd, 0x13, 0x61, 0x0a, 0x73, 0x4b, 0x4a,
	0x44, 0xb5, 0x9a, 0x92, 0xe9, 0xd0, 0x51, 0x21, 0xcf, 0x9a, 0xb2, 0x07, 0x88, 0xf6, 0x6c, 0x08,
	0x11, 0xa2, 0x9a, 0x9b, 0xb1, 0x0e, 0x6f, 0x5c, 0xc2, 0x79, 0x43, 0x52, 0xbb, 0xb6, 0xf3, 0x2d,
	0x7f, 0x25, 0xff, 0x43, 0xf5, 0x1b, 0x65, 0xb7, 0x30, 0x7b, 0x71, 0x0d, 0x39, 0x5c, 0x40, 0x2c,
	0xbe, 0xf4, 0x07, 0x49, 0xa2, 0xb0, 0x1a, 0x52, 0xb6, 0x86, 0xe8, 0x5d, 0xc8, 0xe1, 0x15, 0xcc,
	0x0c, 0xeb, 0x76, 0x3c, 0xd2, 0x87, 0x13, 0x25, 0x5b, 0xb6, 0x66, 0xf8, 0xd4, 0x87, 0xf5, 0x0e,
	0xe2, 0xd7, 0x6f, 0x72, 0xfe, 0x88, 0x8f, 0x00, 0x3b, 0x32, 0x86, 0x3f, 0xd8, 0x99, 0x06, 0x17,
	0x79, 0xef, 0x22, 0x1f, 0x5d, 0xe4, 0xdb, 0x93, 0x8b, 0xf4, 0x0f, 0x9e, 0xfd, 0xab, 0xe2, 0x40,
	0xee, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xf6, 0x4a, 0xbc, 0x5a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// QwertyClient is the client API for Qwerty service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QwertyClient interface {
	HelloWorld(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type qwertyClient struct {
	cc grpc.ClientConnInterface
}

func NewQwertyClient(cc grpc.ClientConnInterface) QwertyClient {
	return &qwertyClient{cc}
}

func (c *qwertyClient) HelloWorld(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.Qwerty/HelloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QwertyServer is the server API for Qwerty service.
type QwertyServer interface {
	HelloWorld(context.Context, *empty.Empty) (*empty.Empty, error)
}

// UnimplementedQwertyServer can be embedded to have forward compatible implementations.
type UnimplementedQwertyServer struct {
}

func (*UnimplementedQwertyServer) HelloWorld(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloWorld not implemented")
}

func RegisterQwertyServer(s *grpc.Server, srv QwertyServer) {
	s.RegisterService(&_Qwerty_serviceDesc, srv)
}

func _Qwerty_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QwertyServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Qwerty/HelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QwertyServer).HelloWorld(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Qwerty_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Qwerty",
	HandlerType: (*QwertyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloWorld",
			Handler:    _Qwerty_HelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modelcore.proto",
}
