// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sun.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestSun struct {
	Text                 string               `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TestSun) Reset()         { *m = TestSun{} }
func (m *TestSun) String() string { return proto.CompactTextString(m) }
func (*TestSun) ProtoMessage()    {}
func (*TestSun) Descriptor() ([]byte, []int) {
	return fileDescriptor_df5d86f47d451473, []int{0}
}

func (m *TestSun) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestSun.Unmarshal(m, b)
}
func (m *TestSun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestSun.Marshal(b, m, deterministic)
}
func (m *TestSun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestSun.Merge(m, src)
}
func (m *TestSun) XXX_Size() int {
	return xxx_messageInfo_TestSun.Size(m)
}
func (m *TestSun) XXX_DiscardUnknown() {
	xxx_messageInfo_TestSun.DiscardUnknown(m)
}

var xxx_messageInfo_TestSun proto.InternalMessageInfo

func (m *TestSun) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *TestSun) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Order struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Number               int64                `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Status               int32                `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_df5d86f47d451473, []int{1}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Order) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Order) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Order) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Order) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Order) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Login                string               `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Price                string               `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	SummaOne             float32              `protobuf:"fixed32,5,opt,name=summa_one,json=summaOne,proto3" json:"summa_one,omitempty"`
	SummaTwo             float64              `protobuf:"fixed64,6,opt,name=summa_two,json=summaTwo,proto3" json:"summa_two,omitempty"`
	Cnt2                 int32                `protobuf:"varint,7,opt,name=cnt2,proto3" json:"cnt2,omitempty"`
	Cnt4                 int64                `protobuf:"varint,8,opt,name=cnt4,proto3" json:"cnt4,omitempty"`
	Cnt8                 int64                `protobuf:"varint,9,opt,name=cnt8,proto3" json:"cnt8,omitempty"`
	IsOnline             bool                 `protobuf:"varint,10,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	Alias                []string             `protobuf:"bytes,11,rep,name=alias,proto3" json:"alias,omitempty"`
	DataByte             []byte               `protobuf:"bytes,12,opt,name=data_byte,json=dataByte,proto3" json:"data_byte,omitempty"`
	Metrika              []byte               `protobuf:"bytes,13,opt,name=metrika,proto3" json:"metrika,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,16,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_df5d86f47d451473, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *User) GetSummaOne() float32 {
	if m != nil {
		return m.SummaOne
	}
	return 0
}

func (m *User) GetSummaTwo() float64 {
	if m != nil {
		return m.SummaTwo
	}
	return 0
}

func (m *User) GetCnt2() int32 {
	if m != nil {
		return m.Cnt2
	}
	return 0
}

func (m *User) GetCnt4() int64 {
	if m != nil {
		return m.Cnt4
	}
	return 0
}

func (m *User) GetCnt8() int64 {
	if m != nil {
		return m.Cnt8
	}
	return 0
}

func (m *User) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

func (m *User) GetAlias() []string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *User) GetDataByte() []byte {
	if m != nil {
		return m.DataByte
	}
	return nil
}

func (m *User) GetMetrika() []byte {
	if m != nil {
		return m.Metrika
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type Role struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_df5d86f47d451473, []int{3}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Role) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*TestSun)(nil), "pb.TestSun")
	proto.RegisterType((*Order)(nil), "pb.Order")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*Role)(nil), "pb.Role")
}

func init() { proto.RegisterFile("sun.proto", fileDescriptor_df5d86f47d451473) }

var fileDescriptor_df5d86f47d451473 = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4f, 0x6b, 0xdc, 0x3e,
	0x10, 0x8d, 0xbd, 0xff, 0x6c, 0x6d, 0x7e, 0xf9, 0x15, 0x51, 0x52, 0xb1, 0x39, 0xd4, 0xec, 0xc9,
	0x97, 0x38, 0xb0, 0xed, 0x21, 0x3d, 0xa6, 0x50, 0x4a, 0xa1, 0xb0, 0x45, 0xdd, 0x42, 0x6f, 0x8b,
	0x6c, 0x4d, 0x17, 0x51, 0x5b, 0x32, 0xd6, 0x98, 0x74, 0x3f, 0x46, 0x3f, 0x66, 0xbf, 0x45, 0x91,
	0xac, 0x2d, 0x61, 0xd3, 0x12, 0x92, 0xdb, 0xbc, 0x37, 0xf3, 0xc6, 0xe3, 0x79, 0x1a, 0x92, 0xda,
	0x5e, 0x17, 0x6d, 0x67, 0xd0, 0xd0, 0xb8, 0x2d, 0x17, 0x2f, 0x77, 0xc6, 0xec, 0x6a, 0xb8, 0xf2,
	0x4c, 0xd9, 0x7f, 0xbb, 0x42, 0xd5, 0x80, 0x45, 0xd1, 0xb4, 0x43, 0xd1, 0xe2, 0xe2, 0xb8, 0x00,
	0x9a, 0x16, 0xf7, 0x43, 0x72, 0xf9, 0x95, 0xcc, 0x36, 0x60, 0xf1, 0x73, 0xaf, 0x29, 0x25, 0x63,
	0x84, 0x1f, 0xc8, 0xa2, 0x2c, 0xca, 0x53, 0xee, 0x63, 0xfa, 0x86, 0x90, 0xaa, 0x03, 0x81, 0x20,
	0xb7, 0x02, 0x59, 0x9c, 0x45, 0xf9, 0x7c, 0xb5, 0x28, 0x86, 0x86, 0xc5, 0xa1, 0x61, 0xb1, 0x39,
	0x7c, 0x91, 0xa7, 0xa1, 0xfa, 0x06, 0x97, 0x3f, 0x63, 0x32, 0x59, 0x77, 0x12, 0x3a, 0x7a, 0x46,
	0x62, 0x25, 0x43, 0xdb, 0x58, 0x49, 0xfa, 0x82, 0xcc, 0x7a, 0x0b, 0xdd, 0x56, 0x49, 0xdf, 0x31,
	0xe5, 0x53, 0x07, 0x3f, 0x48, 0x7a, 0x4e, 0xa6, 0xba, 0x6f, 0x4a, 0xe8, 0xd8, 0x28, 0x8b, 0xf2,
	0x11, 0x0f, 0xc8, 0xf1, 0x16, 0x05, 0xf6, 0x96, 0x8d, 0xb3, 0x28, 0x9f, 0xf0, 0x80, 0x8e, 0xa6,
	0x9b, 0x3c, 0x62, 0x3a, 0x27, 0xed, 0x5b, 0x79, 0x90, 0x4e, 0x1f, 0x96, 0x86, 0xea, 0x41, 0x2a,
	0xa1, 0x86, 0x20, 0x9d, 0x3d, 0x2c, 0x0d, 0xd5, 0x37, 0xb8, 0xfc, 0x35, 0x22, 0xe3, 0x2f, 0xf6,
	0x2f, 0x2b, 0x79, 0x4e, 0x26, 0xb5, 0xd9, 0x29, 0x1d, 0x16, 0x32, 0x00, 0xc7, 0x42, 0x23, 0x54,
	0xed, 0xd7, 0x91, 0xf2, 0x01, 0x38, 0xb6, 0xed, 0x54, 0x05, 0x7e, 0x19, 0x29, 0x1f, 0x00, 0xbd,
	0x70, 0xef, 0xa2, 0x69, 0xc4, 0xd6, 0x68, 0xf0, 0xab, 0x88, 0x79, 0xe2, 0x89, 0xb5, 0xbe, 0x93,
	0xc4, 0x5b, 0xe3, 0x7f, 0x36, 0x0a, 0xc9, 0xcd, 0xad, 0x71, 0xbe, 0x57, 0x1a, 0x57, 0xfe, 0x4f,
	0x26, 0xdc, 0xc7, 0x81, 0x7b, 0xcd, 0x12, 0xef, 0x83, 0x8f, 0x03, 0x77, 0xcd, 0xd2, 0x3f, 0xdc,
	0xb5, 0x6b, 0xac, 0xec, 0xd6, 0xe8, 0x5a, 0x69, 0x60, 0x24, 0x8b, 0xf2, 0x84, 0x27, 0xca, 0xae,
	0x3d, 0x76, 0x83, 0x8a, 0x5a, 0x09, 0xcb, 0xe6, 0xd9, 0xc8, 0x0d, 0xea, 0x81, 0x93, 0x48, 0x81,
	0x62, 0x5b, 0xee, 0x11, 0xd8, 0x69, 0x16, 0xe5, 0xa7, 0x3c, 0x71, 0xc4, 0xdb, 0x3d, 0x02, 0x65,
	0x64, 0xd6, 0x00, 0x76, 0xea, 0xbb, 0x60, 0xff, 0xf9, 0xd4, 0x01, 0x1e, 0x79, 0x7d, 0xf6, 0x74,
	0xaf, 0xff, 0x7f, 0xba, 0xd7, 0xcf, 0x1e, 0xe3, 0xf5, 0x47, 0x32, 0xe6, 0xa6, 0x86, 0x7b, 0x56,
	0xbb, 0x35, 0x1a, 0x09, 0xc1, 0x69, 0x1f, 0xd3, 0x8c, 0xcc, 0x25, 0xd8, 0xaa, 0x53, 0x2d, 0x2a,
	0xa3, 0x83, 0xdd, 0x77, 0xa9, 0x55, 0x45, 0x46, 0xee, 0x46, 0x2f, 0xc9, 0xf8, 0x93, 0xd2, 0x3b,
	0x7a, 0x7e, 0x6f, 0x86, 0x77, 0xee, 0xa8, 0x17, 0xf3, 0xa2, 0x2d, 0x8b, 0x70, 0xd0, 0xcb, 0x13,
	0x7a, 0x49, 0x66, 0xef, 0x01, 0xfd, 0x8b, 0xfb, 0x97, 0x22, 0x71, 0x0a, 0x57, 0xb1, 0x3c, 0x29,
	0xa7, 0x3e, 0xf7, 0xea, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x95, 0xe1, 0xee, 0x62, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SunClient is the client API for Sun service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SunClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TestSun, error)
	GetUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*User, error)
}

type sunClient struct {
	cc grpc.ClientConnInterface
}

func NewSunClient(cc grpc.ClientConnInterface) SunClient {
	return &sunClient{cc}
}

func (c *sunClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TestSun, error) {
	out := new(TestSun)
	err := c.cc.Invoke(ctx, "/pb.Sun/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sunClient) GetUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/pb.Sun/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SunServer is the server API for Sun service.
type SunServer interface {
	Ping(context.Context, *empty.Empty) (*TestSun, error)
	GetUser(context.Context, *empty.Empty) (*User, error)
}

// UnimplementedSunServer can be embedded to have forward compatible implementations.
type UnimplementedSunServer struct {
}

func (*UnimplementedSunServer) Ping(ctx context.Context, req *empty.Empty) (*TestSun, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedSunServer) GetUser(ctx context.Context, req *empty.Empty) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterSunServer(s *grpc.Server, srv SunServer) {
	s.RegisterService(&_Sun_serviceDesc, srv)
}

func _Sun_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SunServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sun/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SunServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sun_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SunServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sun/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SunServer).GetUser(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sun_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Sun",
	HandlerType: (*SunServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Sun_Ping_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Sun_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sun.proto",
}
